apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      restartPolicy: Always
      containers:
      - name: worker
        image: epitechcontent/t-dop-600-worker:k8s
        envFrom:
        - configMapRef:
            name: redis-config
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        resources:
          limits:
            memory: "256M"
            cpu: "0.5"
